# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aliyunInstanceInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('instance_id', models.CharField(unique=True, max_length=50, verbose_name='\u5b9e\u4f8bid')),
                ('instance_name', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u540d\u79f0')),
                ('description', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u63cf\u8ff0')),
                ('image_id', models.CharField(max_length=50, verbose_name='\u955c\u50cfid')),
                ('region_id', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u6240\u5c5e\u5730\u57dfID')),
                ('zone', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u6240\u5c5e\u5730\u57df')),
                ('cpu', models.IntegerField(verbose_name='cpu')),
                ('memory', models.IntegerField(verbose_name='\u5185\u5b58')),
                ('instance_type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u7c7b\u578b')),
                ('instance_type_family', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u89c4\u683c\u65cf')),
                ('hostname', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u673a\u5668\u540d\u79f0')),
                ('serial_number', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u673a\u5668\u7684\u5e8f\u5217\u53f7')),
                ('status', models.CharField(default=b'RUNNING', max_length=50, verbose_name='\u5b9e\u4f8b\u72b6\u6001(PENDING\u51c6\u5907\u4e2d,RUNNING\u8fd0\u884c\u4e2d,STOPPED\u5df2\u505c\u6b62,REBOOTING\u91cd\u542f\u4e2d,STARTING\u542f\u52a8\u4e2d,STOPPING\u505c\u6b62\u4e2d,EXPIRED\u5df2\u8fc7\u671f,TERMINATING\u9000\u8fd8\u4e2d,TERMINATED\u5df2\u9000\u8fd8)')),
                ('security_group_ids', models.CharField(max_length=200, verbose_name='\u5b9e\u4f8b\u6240\u5c5e\u5b89\u5168\u7ec4\u7684\u96c6\u5408')),
                ('public_ip_address', models.CharField(max_length=200, verbose_name='\u5b9e\u4f8b\u7684\u516c\u7f51 IP \u5730\u5740')),
                ('internet_max_bandwidth_in', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u7f51\u7edc\u5e26\u5bbd\u4e0b\u9650')),
                ('internet_max_bandwidth_out', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u7f51\u7edc\u5e26\u5bbd\u4e0a\u9650')),
                ('internet_charge_type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u7f51\u7edc\u8ba1\u8d39\u7c7b\u578b')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5b9e\u4f8b\u521b\u5efa\u65f6\u95f4')),
                ('vpc_attributes', models.CharField(max_length=50, verbose_name='\u4e13\u6709\u7f51\u7edc\u5c5e\u6027')),
                ('eip_address', models.CharField(max_length=50, verbose_name='\u5f39\u6027\u516c\u7f51 IP \u7ed1\u5b9a\u4fe1\u606f')),
                ('inner_ip_address', models.CharField(max_length=50, verbose_name='innerip')),
                ('instance_network_type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u5b9e\u4f8b\u7f51\u7edc\u7c7b\u578b\u3002\u53d6\u503c\u8303\u56f4\uff1aClassic Vpc')),
                ('operation_locks', models.CharField(max_length=200, verbose_name='\u9501\u5b9a\u5217\u8868')),
                ('instance_charge_type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u8ba1\u8d39\u6a21\u5f0fPrePaid\uff1a\u9884\u4ed8\u8d39\uff0c\u5373\u5305\u5e74\u5305\u6708 PostPaid\uff1a\u540e\u4ed8\u8d39\uff0c\u5373\u6309\u91cf\u4ed8\u8d39')),
                ('spot_strategy', models.CharField(max_length=200, verbose_name='\u540e\u4ed8\u8d39\u5b9e\u4f8b\u7684\u7ade\u4ef7\u7b56\u7565 ')),
                ('device_available', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u662f\u5426\u8fd8\u53ef\u4ee5\u6302\u8f7d\u78c1\u76d8')),
                ('deployment_setId', models.CharField(max_length=50, verbose_name='\u90e8\u7f72\u96c6 ID')),
                ('network_interfaces', models.CharField(max_length=200, verbose_name='\u5b9e\u4f8b\u5305\u542b\u7684\u5f39\u6027\u7f51\u5361\u96c6\u5408')),
                ('io_optimized', models.CharField(max_length=50, verbose_name='\u662f\u5426\u662f I/O \u4f18\u5316\u578b\u5b9e\u4f8b')),
                ('expired_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5b9e\u4f8b\u5230\u671f\u65f6\u95f4')),
                ('key_pair_name', models.CharField(max_length=200, verbose_name='\u5bc6\u94a5\u5bf9\u540d\u79f0')),
            ],
            options={
                'db_table': 'aliyun_instance_info',
            },
        ),
        migrations.CreateModel(
            name='QcloudImageInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('image_id', models.CharField(max_length=50, verbose_name='\u955c\u50cfid')),
                ('osname', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u540d\u79f0')),
                ('image_size', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u5bb9\u91cf\uff08GiB\uff09')),
                ('image_type', models.IntegerField(verbose_name='\u955c\u50cf\u7c7b\u578b')),
                ('created_time', models.CharField(max_length=50, verbose_name='\u955c\u50cf\u521b\u5efa\u65f6\u95f4')),
                ('image_state', models.CharField(max_length=50, verbose_name='\u955c\u50cf\u72b6\u6001')),
                ('image_source', models.CharField(max_length=50, verbose_name='\u955c\u50cf\u6765\u6e90')),
                ('image_name', models.CharField(max_length=50, verbose_name='\u955c\u50cf\u540d\u79f0')),
                ('image_description', models.CharField(max_length=50, verbose_name='\u955c\u50cf\u8be6\u7ec6\u63cf\u8ff0')),
                ('image_creator', models.CharField(max_length=50, verbose_name='\u955c\u50cf\u521b\u5efa\u8005')),
                ('operation_mask', models.CharField(max_length=50, verbose_name='')),
            ],
            options={
                'db_table': 'qcloud_image_info',
            },
        ),
        migrations.CreateModel(
            name='QcloudInstanceInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('instance_id', models.CharField(unique=True, max_length=50, verbose_name='\u5b9e\u4f8bid')),
                ('instance_name', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u540d\u79f0')),
                ('instance_type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u7c7b\u578b')),
                ('cpu', models.IntegerField(verbose_name='cpu')),
                ('memory', models.IntegerField(verbose_name='\u5185\u5b58')),
                ('status', models.CharField(default=b'RUNNING', max_length=50, verbose_name='\u5b9e\u4f8b\u72b6\u6001(PENDING\u51c6\u5907\u4e2d,RUNNING\u8fd0\u884c\u4e2d,STOPPED\u5df2\u505c\u6b62,REBOOTING\u91cd\u542f\u4e2d,STARTING\u542f\u52a8\u4e2d,STOPPING\u505c\u6b62\u4e2d,EXPIRED\u5df2\u8fc7\u671f,TERMINATING\u9000\u8fd8\u4e2d,TERMINATED\u5df2\u9000\u8fd8)')),
                ('zone', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u6240\u5c5e\u5730\u57df')),
                ('instance_charge_type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u8ba1\u8d39\u6a21\u5f0f')),
                ('private_ip_addresses', models.CharField(max_length=50, verbose_name='\u5185\u7f51ip')),
                ('public_ip_addresses', models.CharField(max_length=50, verbose_name='\u5916\u7f51ip')),
                ('image_id', models.CharField(max_length=50, verbose_name='\u955c\u50cfid')),
                ('os_name', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u540d\u79f0')),
                ('system_disk_type', models.CharField(max_length=50, verbose_name='\u7cfb\u7edf\u76d8\u7c7b\u578b')),
                ('system_disk_size', models.CharField(max_length=50, verbose_name='\u7cfb\u7edf\u76d8\u5c3a\u5bf8')),
                ('renew_flag', models.CharField(max_length=50, verbose_name='\u81ea\u52a8\u7eed\u8d39\u6807\u8bc6')),
                ('internet_max_bandwidth_out', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u7f51\u7edc\u5e26\u5bbd\u4e0a\u9650')),
                ('internet_charge_type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f8b\u7f51\u7edc\u8ba1\u8d39\u7c7b\u578b')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5b9e\u4f8b\u521b\u5efa\u65f6\u95f4')),
                ('expired_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5b9e\u4f8b\u5230\u671f\u65f6\u95f4')),
            ],
            options={
                'db_table': 'qcloud_instance_info',
            },
        ),
        migrations.CreateModel(
            name='UcloudInstance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('autoRenew', models.CharField(default=b'', max_length=5, null=True)),
                ('basicImageId', models.CharField(default=b'', max_length=15, null=True)),
                ('basicImageName', models.CharField(default=b'', max_length=30, null=True)),
                ('bootDiskState', models.CharField(default=b'', max_length=10, null=True)),
                ('cpu', models.IntegerField(default=0, null=True)),
                ('chargeType', models.CharField(default=b'', max_length=15, null=True)),
                ('createTime', models.TimeField(null=True)),
                ('backupType', models.CharField(default=b'', max_length=15, null=True)),
                ('diskId', models.CharField(default=b'', max_length=15, null=True, verbose_name='\u78c1\u76d8id')),
                ('drive', models.CharField(default=b'', max_length=15, null=True, verbose_name='\u78c1\u76d8\u9a71\u52a8')),
                ('encrypted', models.CharField(default=b'No', max_length=5, null=True, verbose_name='\u78c1\u76d8\u662f\u5426\u52a0\u5bc6')),
                ('size', models.IntegerField(default=0, null=True, verbose_name='\u78c1\u76d8\u5927\u5c0f')),
                ('type', models.CharField(default=b'Boot', max_length=10, null=True, verbose_name='\u78c1\u76d8\u7c7b\u578b')),
                ('expireTime', models.TimeField(null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('gpu', models.IntegerField(default=0, null=True, verbose_name='\u662f\u5426\u5f00\u542fGPU')),
                ('hostType', models.CharField(default=b'', max_length=10, null=True, verbose_name='\u4e3b\u673a\u7c7b\u578b')),
                ('hotplugFeature', models.BooleanField(default=False, max_length=10, verbose_name='\u662f\u5426\u70ed\u63d2\u62d4\u7279\u6027')),
                ('privateSubnetId', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u79c1\u6709\u5b50\u7f51id')),
                ('privateIP', models.CharField(default=b'', max_length=20, null=True, verbose_name='')),
                ('privateVPCId', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u5b50\u7f51VPCid')),
                ('publicBandwidth', models.IntegerField(default=0, null=True, verbose_name='\u516c\u5171\u5e26\u5bbd')),
                ('publicIP', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u516c\u5171IP')),
                ('publicIPId', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u516c\u5171IPid')),
                ('publicType', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u516c\u5171IP\u7c7b\u578b')),
                ('publicWeight', models.IntegerField(default=0, null=True, verbose_name='\u6743\u91cd')),
                ('imageId', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u955c\u50cfID')),
                ('isExpire', models.CharField(default=b'No', max_length=5, null=True, verbose_name='\u662f\u5426\u8fc7\u671f')),
                ('memory', models.IntegerField(default=0, null=True, verbose_name='\u5185\u5b58')),
                ('name', models.CharField(default=b'', max_length=40, verbose_name='\u540d\u79f0')),
                ('netCapFeature', models.BooleanField(default=False)),
                ('netCapability', models.CharField(default=b'Normal', max_length=20, null=True)),
                ('networkState', models.CharField(default=b'NotConnected', max_length=20, null=True)),
                ('osName', models.CharField(default=b'', max_length=30, null=True)),
                ('osType', models.CharField(default=b'', max_length=10, null=True)),
                ('remark', models.CharField(default=b'', max_length=100, null=True)),
                ('state', models.CharField(default=b'', max_length=15, null=True)),
                ('storageType', models.CharField(default=b'', max_length=15, null=True)),
                ('subnetType', models.CharField(default=b'', max_length=15, null=True)),
                ('tag', models.CharField(default=b'', max_length=15, null=True)),
                ('timemachineFeature', models.CharField(default=b'', max_length=5, null=True)),
                ('totalDiskSpace', models.IntegerField(default=0, null=True)),
                ('uHostId', models.CharField(default=b'', max_length=15, null=True)),
                ('uHostType', models.CharField(default=b'', max_length=15, null=True)),
                ('zone', models.CharField(default=b'', max_length=20, null=True)),
            ],
            options={
                'db_table': 'ucloud_instance_info',
            },
        ),
        migrations.CreateModel(
            name='VcenterAccount',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('account_name', models.CharField(max_length=60)),
                ('account_password', models.CharField(default=b'', max_length=60, null=True)),
                ('vcenter_host', models.CharField(default=b'', max_length=30, null=True)),
                ('vcenter_port', models.IntegerField(default=443, null=True)),
                ('vcenter_version', models.CharField(default=b'', max_length=10, null=True)),
                ('cloud_provider', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u4e91\u63d0\u4f9b\u5546')),
                ('cloud_private_key', models.CharField(default=b'', max_length=60, null=True, verbose_name='\u4e91\u79c1\u94a5\u5319')),
                ('cloud_public_key', models.CharField(default=b'', max_length=60, null=True, verbose_name='\u4e91\u516c\u94a5\u5319')),
                ('cloud_region', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u4e91\u533a\u57df')),
                ('project_id', models.CharField(default=b'', max_length=20, null=True, verbose_name='\u4e91\u9879\u76ee')),
            ],
            options={
                'db_table': 'vcenter_account',
            },
        ),
        migrations.CreateModel(
            name='VcenterCluster',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=60)),
                ('actionHistoryNum', models.IntegerField(default=0)),
                ('migrationHistoryNum', models.IntegerField(default=0)),
                ('drsRecommendationNum', models.IntegerField(default=0)),
                ('enabledClusterHa', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vcenter_cluster',
            },
        ),
        migrations.CreateModel(
            name='VcenterDatacenter',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=60)),
                ('datastoreTotal', models.IntegerField(default=0)),
                ('datastoreNum', models.IntegerField(default=0)),
                ('hostNum', models.IntegerField(default=0)),
                ('networkNum', models.IntegerField(default=0)),
                ('vmNum', models.IntegerField(default=0)),
                ('clusterNum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vcenter_datacenter',
            },
        ),
        migrations.CreateModel(
            name='VcenterDatastore',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=60)),
                ('mountHostNum', models.IntegerField(default=0)),
                ('datastoreContainerId', models.CharField(default=b'', max_length=60, null=True)),
                ('accessible', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=0)),
                ('freeSpace', models.IntegerField(default=0)),
                ('maintenanceMode', models.CharField(default=b'', max_length=20)),
                ('multipleHostAccess', models.BooleanField(default=True, max_length=20)),
                ('filesystemType', models.CharField(default=b'', max_length=20)),
                ('url', models.CharField(default=b'', max_length=120)),
                ('datacenter', models.ForeignKey(related_name='vcenter_datastore_ref_datacenter', to='home_application.VcenterDatacenter')),
            ],
            options={
                'db_table': 'vcenter_datastore',
            },
        ),
        migrations.CreateModel(
            name='VcenterHost',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'', max_length=60)),
                ('api_type', models.CharField(default=b'', max_length=20)),
                ('api_version', models.CharField(default=b'', max_length=20)),
                ('build', models.CharField(default=b'', max_length=20)),
                ('full_name', models.CharField(default=b'', max_length=60)),
                ('instance_uuid', models.CharField(default=b'', max_length=40)),
                ('license_product_name', models.CharField(default=b'', max_length=20)),
                ('license_product_version', models.CharField(default=b'', max_length=20)),
                ('locale_build', models.CharField(default=b'', max_length=20)),
                ('locale_version', models.CharField(default=b'', max_length=20)),
                ('os_type', models.CharField(default=b'', max_length=20)),
                ('product_line_id', models.CharField(default=b'', max_length=20)),
                ('vendor', models.CharField(default=b'', max_length=20)),
                ('version', models.CharField(default=b'', max_length=20)),
            ],
            options={
                'db_table': 'vcenter_host',
            },
        ),
        migrations.CreateModel(
            name='VcenterNetwork',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'', max_length=60)),
                ('host', models.CharField(default=b'', max_length=32)),
                ('mtu', models.IntegerField(default=0)),
                ('num_ports', models.IntegerField(default=0)),
                ('num_ports_available', models.IntegerField(default=0)),
                ('portgroup', models.CharField(default=b'', max_length=120)),
                ('vnic', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vcenter_network',
            },
        ),
        migrations.CreateModel(
            name='VcenterVirtualMachine',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=60)),
                ('vm_pathname', models.CharField(max_length=120)),
                ('guest_fullname', models.CharField(max_length=60)),
                ('power_state', models.CharField(max_length=50)),
                ('ipaddress', models.CharField(max_length=30)),
                ('instance_uuid', models.CharField(unique=True, max_length=40)),
                ('boot_time', models.TimeField(null=True)),
                ('template', models.BooleanField(default=False)),
                ('maxCpuUsage', models.IntegerField(default=0)),
                ('maxMemoryUsage', models.IntegerField(default=0)),
                ('memorySizeMB', models.IntegerField(default=0)),
                ('numCpu', models.IntegerField(default=0)),
                ('numEthernetCards', models.IntegerField(default=0)),
                ('numVirtualDisks', models.IntegerField(default=0)),
                ('instanceUuid', models.CharField(max_length=60)),
                ('guestId', models.CharField(max_length=60)),
                ('overallStatus', models.CharField(max_length=10)),
                ('account', models.ForeignKey(related_name='vcenter_virtualmachine_ref_account', to='home_application.VcenterAccount')),
                ('cluster', models.ForeignKey(related_name='vcenter_virtualmachine_ref_cluster', to='home_application.VcenterCluster', null=True)),
                ('datacenter', models.ForeignKey(related_name='vcenter_virtualmachine_ref_datacenter', to='home_application.VcenterDatacenter', null=True)),
            ],
            options={
                'db_table': 'vcenter_virtualmachine',
            },
        ),
        migrations.CreateModel(
            name='VcenterVirtualMachineSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=120, verbose_name='\u5feb\u7167\u540d\u79f0')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='\u5feb\u7167\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('result', models.CharField(default=b'running', max_length=20, verbose_name='\u521b\u5efa\u5feb\u7167\u7ed3\u679c:running\u8868\u793a\u6b63\u5728\u521b\u5efa\u4e2d\uff0csuccess\u8868\u793a\u521b\u5efa\u5feb\u7167\u6210\u529f\uff0cfailed\u8868\u793a\u521b\u5efa\u5931\u8d25')),
                ('account', models.ForeignKey(related_name='vcenter_virtualMachine_napshot_ref_account', to='home_application.VcenterAccount')),
                ('virtualmachine', models.ForeignKey(related_name='vcenter_virtualMachine_napshot_ref_virtualmachine', to='home_application.VcenterVirtualMachine')),
            ],
            options={
                'db_table': 'vcenter_virtualmachine_snapshot',
            },
        ),
        migrations.AddField(
            model_name='vcentercluster',
            name='datacenter',
            field=models.ForeignKey(related_name='vcenter_cluster_ref_datacenter', to='home_application.VcenterDatacenter'),
        ),
    ]
